#!/bin/bash
cd `dirname $0`

if test -z $1
then {
    export VARIANTS=debug
} else {
    export VARIANTS=$*
}
fi

if test -e /proc/
then {
    export CPUCOUNT=`grep -c ^processor /proc/cpuinfo`
    [ `which clang++` ] || export TOOLSET=toolset=gcc
    export LD_LIBRARY_PATH=../dist/lib
}
else {
    export CPUCOUNT=`sysctl -n hw.ncpu`
    export TOOLSET=toolset=darwin
    export DYLD_LIBRARY_PATH=../dist/lib
    export LANG=C
}
fi

if ../bjam -j$CPUCOUNT $TOOLSET $VARIANTS `../python.opts.sh`
then {
    echo fost-internet $VARIANTS OK
    exit 0
} else {
    exit 1
}
fi
